
const Data = {
  tr: {
    skills: 'Yetenekler',
    projects: 'Projeler',
    hire: 'İşe Alım',
    hireDescription: 'Merhaba, Ben Kubilay. Tam yığın geliştiriciyim. Eğer sağlam ',
    hireDescription1:"ve ölçeklenebilir ön uç ürünleri üretmek için bir geliştirici arıyorsanız ",
    hireDescription2:"harika kullanıcı deneyimleri ile birlikte; El sıkışalım ve konuşalım.",
    profile:"Profil",
    BirthDate:"Doğum tarihi",
    JavaScript:" JavaScript, çeşitli interaktif ve dinamik web öğeleri oluşturmak için kullanabilirim. Web sayfalarına kullanıcı etkileşimleri eklemek, form doğrulaması yapmak, görsel efektler eklemek, verileri dinamik olarak güncellemek, API'lar aracılığıyla sunucu ile iletişim kurmak ve hatta oyunlar gibi kompleks uygulamalar geliştirmek için kullanabilirim.",
    React:"React, modern web ve mobil uygulamalar geliştirmek için kullanılan bir JavaScript kütüphanesidir. Bileşen tabanlı bir yaklaşıma dayanarak, kullanıcı arayüzünü hızlı ve etkili bir şekilde oluşturmamı sağlar. Veri akışını yönetmek için tek yönlü bağlantı sunar, bu da uygulamaların daha öngörülebilir olmasını sağlar. Böylece büyük ve karmaşık uygulamaları bile parçalara ayırarak geliştirebilirim.",
    Java:"Java, çok amaçlı bir programlama dilidir ve genellikle çeşitli platformlarda kullanılan uygulamaların geliştirilmesinde tercih edilir. Nesne yönelimli bir yaklaşıma sahiptir, yani kodun farklı bileşenleri olan nesneler arasındaki etkileşime odaklanır. Java'nın platform bağımsız bir özelliği vardır, bu da aynı kodun farklı işletim sistemlerinde çalışabilmesini sağlar. Geniş bir standart kütüphane içerir ve web uygulamalarından mobil uygulamalara kadar çeşitli alanlarda kullanabilirim.",
    City:"İkamet Şehri",
    Education:"Eğitim Durumu",
    Role:"Tercih Ettiği Rol",
    AboutHead:"Benim Hakkımda",
    About:"Web siteleri oluşturmayı seven bir Biyomedikal Mühendisi ve Front-End Web Geliştiricisiyim. Banner oluşturma ve animasyonları (GSAP) üzerinde çalıştım ve ayrıca uyumlu Outlook ve Karanlık Mod Dostu Postalar ve mobil platformlarla Responsive E-Posta üzerinde çalıştım. E-Posta Asitini test ediyorum. Son olarak Açılış Sayfaları ve E-İçerikler üzerinde çalıştım. Sorun çözme konusunda araştırmacı bir kişiliğe sahibim ve yenilikçi bir insanım.",
    University:"Bahçeşehir Ünv. Biyomedikal",
    University1:"Lisans,2019",
    Project1:"Alışveriş Sepeti",
    Project1Text:"Bu modülde, bir e-ticaret aracı olan 'Context API'yi kullanarak yeni edindiğimiz 'Context API' bilgimizi yeniden düzenledik ve kullanımını daha sağlam hale getirmek için genişlettik!",
    View:"Siteyi ziyaret et",
    Projects:"Projeler",
    Project2:"Film İzleme Listesi",
    Project2Text:"Bu proje, öğrendiğimiz redux kavramlarını ve yöntemlerini uyguladığımız, logger ara yazılımı ile redux adımlarını takip ettiğimiz küçük bir film izleme listesi oluşturma projesidir.",
    Project3:"Hesap Makinesi",
    Project3Text:"Bu projede, herhangi bir sırayla toplama, çarpma, çıkarma ve bölme işlemleri yapabilen, ayrıca hafıza kaydetme ve geri arama özellikleri ekleyen basit bir hesap makinesi uygulaması oluşturduk.",
    FooterTitle:"Bir sonraki ürününüz",
    FooterTitle1:"üzerinde birlikte çalışalım.",
    Blog:"Kişisel Blog"
  },
  en: {
    skills: 'Skills',
    projects: 'Projects',
    hire: 'Hire me',
    hireDescription:"Hi, I’m Kubilay. I’m a full-stack developer. If you are looking for a ",
    hireDescription1:"Developer who to craft solid and scalable frontend products with",
    hireDescription2:"great user experiences; Let's shake hands with me.",
    profile:"Profile",
    BirthDate:"Birth Date",
    JavaScript:"I can use JavaScript to create various interactive and dynamic web elements. It's utilized to add user interactions to web pages, perform form validation, add visual effects, dynamically update data, communicate with servers through APIs, and even develop complex applications like games.",
    React:"React is a JavaScript library used to develop modern web and mobile applications. It's based on a component-based approach, allowing me to create user interfaces quickly and effectively. It provides one-way data binding to manage data flow, making applications more predictable. This enables me to develop even large and complex applications by breaking them down into components.",
    Java:"Java is a multi-purpose programming language and is often preferred for execution used on various platforms. It has an implementation that is part of objects, that is, it focuses on the interaction between objects that are different components of the code. Java has a platform independent feature, but ensures that the same code can run on different operating systems. It includes a wide standard package and can be used in a variety of areas from web apps to mobile apps.",
    City:"City of Residence",
    Education:"Education",
    Role:"Preferred Role",
    AboutHead:"About Me",
    About:"I am a Biomedical Engineer and Front-End Web Developer who loves to build websites. I have worked on banner creation and animations (GSAP) and also worked on compatible Outlook and Dark Mode Friendly Mail and Responsive Email with mobile platforms. I'm testing E-Mail Acid. Lastly, I worked on Landing Pages and E-Contents. I have an investigative personality in problem solving and I am an innovative person.",
    University:"Bahçeşehir Ünv. Biomedical",
    University1:"Master Degree,2019",
    Project1:"Shopping Cart",
    Project1Text:"In this module, we've reworked our newly acquired knowledge of 'Context API' using an e-commerce tool 'Context API' and expanded its use to make it more robust!",
    View:"View Site",
    Projects:"Projects",
    Project2:"Movie Watch List",
    Project2Text:"This project is a small movie watchlist creation project where we apply the redux concepts and methods we learned, and follow the redux steps with the logger middleware.",
    Project3:"Reducer Calculator",
    Project3Text:"In this project, addition, multiplication, subtraction, and division can be performed in any order, as well as a simple calculator application that adds memory recording and callback features.",
    FooterTitle:"Let’s work together on",
    FooterTitle1:" your next product.",
    Blog:"Personal Blog"
  },
};

export default Data;
